server:
  port: 8083

spring:
  application:
    name: trade-service
  profiles:
    default: local
  cloud:
    nacos:
      discovery:
        server-addr: ${ke.addr}:8848
        ip: ${ke.ip}
      config:
        server-addr: ${ke.addr}:8848
        file-extension: yaml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ke.addr}:3306/trade_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

  redis:
    host: redis
    port: 6379
  rabbitmq:
    host: ${ke.addr}
    port: 5672
    username: admin
    password: 123456
    virtual-host: /kemall
    connection-timeout: 5s
    publisher-confirm-type: correlated

dubbo:
  application:
    name: trade-service
    qos-enable: false
  registry:
    address: nacos://${ke.addr}:8848
  protocol:
    name: dubbo
  scan:
    base-packages: com.kemall.trade.service
  consumer:
    check: false

seata:
  enabled: true
  application-id: trade-service
  tx-service-group: default_tx_group
  enable-auto-data-source-proxy: false

  # 不使用 Nacos 服务发现
  registry:
    type: file

  config:
    type: file

  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: ${ke.addr}:8091  # 直连宿主机 IP
