server:
  port: 10010

spring:
  application:
    name: kemall-gateway
  profiles:
    default: dev
  cloud:
    nacos:
      discovery:
        server-addr: ${ke.addr}:8848
        ip: ${ke.ip}
      config:
        server-addr: ${ke.addr}:8848
        file-extension: yaml
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          filters:
            - StripPrefix=0
          predicates:
            - Path=/users/**


jwt:
  secret: kemallSecretKey12345678901234567890