server:
  port: 8085

spring:
  application:
    name: inventory-service
  profiles:
    default: dev
  cloud:
    nacos:
      discovery:
        server-addr: ${ke.addr}:8848
        ip: ${ke.ip}
      config:
        server-addr: ${ke.addr}:8848
        file-extension: yaml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ke.addr}:3306/inventory_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

  redis:
    host: redis
    port: 6379

seata:
  enabled: true
  application-id: ${spring.application.name}
  # 事务分组，TC端 service.vgroupMapping 中需要配置相同的分组
  tx-service-group: kemall-tx-group
  service:
    vgroup-mapping:
      kemall-tx-group: default
  # 通过nacos发现seata-server
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${ke.addr}:8848
      group: DEFAULT_GROUP
      namespace: ""
      username: nacos
      password: nacos

